### ISSUE TITLE
Weird behavior with @var Foo|Bar

### ISSUE THREAD

**Issue by Majkl578** [Kdyby/Autowired#11]
Having `@var \Nette\Localization\ITranslator|\App\Translator` leads to a weird exception `Class "Nette\Localization\ITranslator|\App\Translator" was not found`.

**Comment by xificurk** [comment]
I don't think that union type is a valid use-case. The component should specify what it really depends on - either a specific implementation or some abstraction. Nette DI does not support wiring by intersection or union type either.

The exception message is improved with typed properties that have union or intersection type. Parsing type from phpdoc annotation will be dropped in next major version.
