### ISSUE TITLE
nette 2.4 compatibility

### ISSUE THREAD

**Issue by Lopo** [Kdyby/Autowired#21]
`Argument 1 passed to App\Presenters\Base::validateProperty() must be an instance of Nette\Reflection\Property, instance of ReflectionProperty given, called in ..../vendor/kdyby/autowired/src/Kdyby/Autowired/AutowireProperties.php on line 78`

**Comment by hrach** [comment]
This issue shoulb be imo opened in nette.

**Comment by tomaj** [comment]
```Fatal error: Call to undefined method ReflectionParameter::getClassName() in .../vendor/kdyby/autowired/src/Kdyby/Autowired/AutowireComponentFactories.php on line 82 ```

**Comment by fprochazka** [comment]
Should be solved now.
